name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './Project_B_Server/appsettings.json'
      env:
        MongoDB.ConnectionUri: ${{ secrets.MONGO_CONNECTION_URI }}
