name: CI_CD

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './Project_B_Server/appsettings.json'
      env:
        MongoDB.ConnectionUri: ${{ secrets.MONGO_CONNECTION_URI }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Deploy Docker Image to Heroku App
      id: heroku
      uses: mtsmachado8/heroku-deploy@v2.0.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        api_key: ${{ secrets.HEROKU_API_KEY }}
        app_name: project-b-server
        dockerfile_path: ''
        options: ''
          
